### PR TITLE
Highlight current tree

### PR DESCRIPTION
**Pull request by bjarnef**
Highlight the current tree #29

### CODE REVIEW

**Comment by Jeavon** [comment]
@bjarnef can you checkout the latest develop branch on your local machine, merge in your changes from your local master branch, push to your GitHub fork, then you can create a PR from your new develop branch? Does that make sense?

**Comment by Jeavon** [comment]
Nearly, you need to take appveyor.yml from the develop branch and commit to your branch and I think it will build!

**Comment by bjarnef** [comment]
I created a new branch and submitted a PR here: https://github.com/warrenbuckley/Analytics/pull/36

**Comment by Jeavon** [comment]
Looks good, well done for sticking with it!

**Pull request closed without merging**
