### PR TITLE
Typo in itemTransactions

### PR DESCRIPTION
**Pull request by bjarnef**
It seems it wasn't merged correctly to master branch last time.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
@bjarnef I thought I mentioned this to you but we intend to try and use a GitFlow approach to this repo so any new features are created with a feature branch.

Can you verify your change is in a different branch such as develop please?

The goal is to use AppVeyor to do automated umbraco & nuget package builds from every commit to the GitHub repo.

Every commit/merge into the master branch is a release and will push to NuGet from memory, but as we got stuck on an issue before I release, I've forgotten how this is setup.

Cheers,
Warren :)

**Comment by Jeavon** [comment]
This PR should to be targeted to the develop branch, not master, then the build should pass.

**Comment by bjarnef** [comment]
@warrenbuckley okay, I didn't noticed there have been created a "develop" branch too.. I will change to develop-branch.

**Comment by Jeavon** [comment]
@warrenbuckley I would suggest you change the default branch to "develop" :)

**Comment by warrenbuckley** [comment]
@Jeavon how do i do that?

**Comment by bjarnef** [comment]
@warrenbuckley in the settings for the repository you can set the default branch.

**Pull request closed without merging**
